client_config_backend: settings
client_config:
  client_id: 221128656797-t5co5lsmgh3uib49h8n1h06fl1eea9q2.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive