# Generated by Django 3.2.14 on 2022-08-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('ruta', models.FileField(upload_to='sounds/')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
