# Generated by Django 3.2.14 on 2022-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ruta_audio_clonado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
